server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Charithharsha08/config-files.git
          clone-on-start: true
          default-label: master